//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPFS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SPFSContext : DbContext
    {
        public SPFSContext()
            : base("name=SPFSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SPFS_ROLES> SPFS_ROLES { get; set; }
        public virtual DbSet<SPFS_SITES> SPFS_SITES { get; set; }
        public virtual DbSet<SPFS_SPEND_SUPPLIERS> SPFS_SPEND_SUPPLIERS { get; set; }
        public virtual DbSet<SPFS_SUPPLIERS> SPFS_SUPPLIERS { get; set; }
        public virtual DbSet<SPFS_USERS> SPFS_USERS { get; set; }
        public virtual DbSet<SPFS_USERSITES> SPFS_USERSITES { get; set; }
        public virtual DbSet<SPFS_LINK_ERP> SPFS_LINK_ERP { get; set; }
        public virtual DbSet<SPFS_STAGING_SUPPLIER_RATINGS> SPFS_STAGING_SUPPLIER_RATINGS { get; set; }
        public virtual DbSet<SPFS_SUPPLIER_RATINGS> SPFS_SUPPLIER_RATINGS { get; set; }
    }
}
